Repository MarinaFX/Fiero, pull requests merged in 2022-10, with the labels that each got.

#267 Bugfix/segue to details fails when server off
  Fiero.xcodeproj/project.pbxproj
  Fiero/FieroAPI.swift
  Fiero/ViewModel/QuickChallengeViewModel.swift
  Fiero/ViewModel/UserViewModel.swift
  Fiero/Views/Challenges/ChallengesListScreenView.swift
  Fiero/Views/Challenges/EmptyChallengesView.swift
Labels: UI 🎨, Back-end ⚙️, Combine 🪖

#289 BUGFIX/TK10 Fix Create Challenge Screens to support smaller devices
  Fiero/Views/Challenges/Quick/QCCategorySelectionView.swift
  Fiero/Views/Challenges/Quick/QCChallengeCreatedView.swift
  Fiero/Views/DesignSystem/Components/TextFields/PermanentKeyboard.swift
  en.lproj/Localizable.strings
Labels: bugfix 🧯, UI 🎨, Accessibility ♥️

#290 BUGFIX/TK12 Fix Challenge Detail Screens to support smaller devices
  Fiero/Views/Challenges/Quick/Details/ChallengeDetailsView.swift
Labels: bugfix 🧯, UI 🎨, Accessibility ♥️

#292 Bugfix/TK12 Fix challenge details screens to support smaller devices
  Fiero/Views/Challenges/Quick/Details/ChallengeDetailsView.swift
Labels: bugfix 🧯, UI 🎨, Accessibility ♥️

#293 feat: add account recovery localization
  en.lproj/Localizable.strings
  pt-BR.lproj/Localizable.strings
Labels: Feature ✨, UI 🎨, Accessibility ♥️

#294 Optimize login and signup screen and Animation
  Fiero.xcodeproj/project.pbxproj
  Fiero/LottieView.swift
  Fiero/ViewModel/UserViewModel.swift
  Fiero/Views/Challenges/EmptyChallengesView.swift
  Fiero/Views/Challenges/Quick/Details/ChallengeDetailsView.swift
  Fiero/Views/Challenges/Quick/Details/ChallengeListCell.swift
  Fiero/Views/Challenges/Quick/Ongoing/WinScreen.swift
  Fiero/Views/Challenges/Quick/QCChallengeCreatedView.swift
  Fiero/Views/DesignSystem/Components/Card/CategoryView/ChallengeCategoryCardView.swift
  Fiero/Views/Login/AccountLoginView.swift
  Fiero/Views/Login/LoginAlertCases.swift
  Fiero/Views/Login/SignupAlertCases.swift
  Fiero/Views/Login/UserSignupView.swift
  Fiero/Views/Profile/ProfileView.swift
Labels: bugfix 🧯, UI 🎨, Improvements ❤️‍🩹, Major Changes ☢️

#291 feat: finish refresh token when app becomes active
  Fiero.xcodeproj/project.pbxproj
  Fiero/App/FieroApp.swift
  Fiero/AuthTokenService.swift
  Fiero/Extensions/Data+Extensions.swift
  Fiero/Extensions/String+Extensions.swift
  Fiero/ViewModel/QuickChallengeViewModel.swift
  Fiero/ViewModel/UserViewModel.swift
  Fiero/Views/Challenges/Quick/Amount/QCAmountWinRulesView.swift
  Fiero/Views/Challenges/Quick/QCChallengeCreatedView.swift
  Fiero/Views/ContentView.swift
  Fiero/Views/Profile/ProfileView.swift
  FieroTests/Challenges/QuickChallengeViewModelTests.swift
  FieroTests/Login+Registration/UserLoginViewModelTests.swift
  FieroTests/Login+Registration/UserRegistrationViewModelTests.swift
Labels: bugfix 🧯, Back-end ⚙️, WIP 🚧, Combine 🪖, Major Changes ☢️

#295 Feature/tk80 develop account recovery screen api integration
  Fiero/FieroAPI.swift
  Fiero/ViewModel/UserViewModel.swift
  Fiero/Views/Profile/ProfileView.swift
Labels: Back-end ⚙️, Combine 🪖

#296 Feature/tk81 develop recovery code screen and password definition screen
  Fiero/Extensions/URLSession+Extensions.swift
  Fiero/ViewModel/UserViewModel.swift
  Fiero/Views/Profile/ProfileView.swift
Labels: Feature ✨, Back-end ⚙️, Combine 🪖

#297 Recover Password flow
  Fiero.xcodeproj/project.pbxproj
  Fiero/Views/DesignSystem/Components/TextFields/CustomTextFieldView.swift
  Fiero/Views/Login/AccountLoginView.swift
  Fiero/Views/Login/Recover Password/InputConfirmationCode.swift
  Fiero/Views/Login/Recover Password/RecoverPasswordEmailStep.swift
  en.lproj/Localizable.strings
  pt-BR.lproj/Localizable.strings
Labels: Feature ✨, UI 🎨, Improvements ❤️‍🩹

#298 fix: saved password after successfully reseting
  Fiero/AuthTokenService.swift
  Fiero/ViewModel/UserViewModel.swift
Labels: Back-end ⚙️, Hotfix 🚨

#301 Feature/TK76 develop sound component controller
  Fiero.xcodeproj/project.pbxproj
  Fiero/App/FieroApp.swift
  Fiero/Players/SoundPlayer.swift
Labels: Feature ✨

#303 Bugfix/TK11 Fix Ongoing Screens to support smaller devices
  Fiero.xcodeproj/project.pbxproj
  Fiero/Views/Challenges/Quick/Details/ChallengeDetailsView.swift
  Fiero/Views/Challenges/Quick/Ongoing/DuelScreenView.swift
  Fiero/Views/Challenges/Quick/Ongoing/Ongoing3_4ScreenView.swift
  Fiero/Views/Challenges/Quick/Ongoing/OngoingDuelScreenView.swift
  Fiero/Views/Challenges/Quick/Ongoing/OngoingScreen.swift
  Fiero/Views/Challenges/Quick/Ongoing/OngoingWithPause.swift
  Fiero/Views/Challenges/Quick/Ongoing/PauseScreen.swift
  Fiero/Views/Challenges/Quick/QCChallengeCreatedView.swift
  Fiero/Views/DesignSystem/Components/ScoreControllers/ScoreController3-4/ScoreController3-4Component.swift
Labels: bugfix 🧯, UI 🎨, Accessibility ♥️

#300 Tk73 login/signup screen support smaller devices
  Fiero.xcodeproj/project.pbxproj
  Fiero/Views/Login/AccountLoginView.swift
  Fiero/Views/Login/Recover Password/InputConfirmationCode.swift
  Fiero/Views/Login/Recover Password/InputConfirmationCodeView.swift
  Fiero/Views/Login/Recover Password/RecoverPasswordEmailStepView.swift
  en.lproj/Localizable.strings
  pt-BR.lproj/Localizable.strings
Labels: Feature ✨, bugfix 🧯, UI 🎨, Improvements ❤️‍🩹

#304 Feature/tk49 develop interaction sound
  Fiero.xcodeproj/project.pbxproj
  Fiero/Assets/Assets.xcassets/Sounds/Contents.json
  Fiero/Assets/Assets.xcassets/Sounds/cavalo.dataset/Contents.json
  Fiero/Assets/Assets.xcassets/Sounds/cavalo.dataset/cavalo.mp3
  Fiero/Assets/Assets.xcassets/Sounds/metal.dataset/Contents.json
  Fiero/Assets/Assets.xcassets/Sounds/metal.dataset/decisive.mp3
  Fiero/Assets/Assets.xcassets/Sounds/negativePoint.dataset/Contents.json
  Fiero/Assets/Assets.xcassets/Sounds/negativePoint.dataset/negativePoint.wav
  Fiero/Assets/Assets.xcassets/Sounds/positivePoint.dataset/Contents.json
  Fiero/Assets/Assets.xcassets/Sounds/positivePoint.dataset/positivePoint.wav
  Fiero/Players/SoundPlayer.swift
  Fiero/Views/Challenges/Quick/QCCategorySelectionView.swift
  Fiero/Views/DesignSystem/Components/ScoreControllers/ScoreController3-4/ScoreController3-4Component.swift
  pt-BR.lproj/Localizable.strings
Labels: Feature ✨

#302 Feature/tk18 develop alert when email is not valid for account recovery
  Fiero.xcodeproj/project.pbxproj
  Fiero.xcodeproj/xcshareddata/xcschemes/Fiero.xcscheme
  Fiero/AuthTokenService.swift
  Fiero/Extensions/Enums/ActiveAlertEnum.swift
  Fiero/Extensions/Enums/FieroAPI.swift
  Fiero/Extensions/Enums/QCTypeEnum.swift
  Fiero/Extensions/Enums/RecoveryAccountErrorCases.swift
  Fiero/Extensions/Enums/UDKeysEnum.swift
  Fiero/Extensions/URLSession+Extensions.swift
  Fiero/HTTPClient.swift
  Fiero/Haptics.swift
  Fiero/ViewModel/QuickChallengeViewModel.swift
  Fiero/ViewModel/UserViewModel.swift
  Fiero/Views/Challenges/Quick/Amount/QCAmountWinRulesView.swift
  Fiero/Views/Challenges/Quick/Details/ChallengeListCell.swift
  Fiero/Views/Challenges/Quick/QCChallengeCreatedView.swift
  Fiero/Views/Challenges/Quick/QCNamingView.swift
  Fiero/Views/Challenges/Quick/QCSelectParticipantsView.swift
  Fiero/Views/Challenges/WIP/BestOf/BestOfChallengeWinRulesView.swift
  Fiero/Views/Challenges/WIP/Time/TimeChallengeWinRulesView.swift
  Fiero/Views/Challenges/WIP/Time/TimePickerSelectionView.swift
  Fiero/Views/ContentView.swift
  Fiero/Views/Login/AccountLoginView.swift
  Fiero/Views/Login/Recover Password/InputConfirmationCodeView.swift
  Fiero/Views/Login/Recover Password/RecoverPasswordEmailStepView.swift
  Fiero/Views/TabBar.swift
  en.lproj/Localizable.strings
  pt-BR.lproj/Localizable.strings
Labels: Feature ✨, UI 🎨, Back-end ⚙️, Improvements ❤️‍🩹, Combine 🪖, Major Changes ☢️

#305 style: fix color button
  Fiero/Views/DesignSystem/Components/Button/ButtonStyles.swift
  Fiero/Views/Login/AccountLoginView.swift
Labels: UI 🎨, Improvements ❤️‍🩹, Accessibility ♥️

#306 feat: Haptics controller
  Fiero/Players/HapticsController.swift
  Fiero/Views/Challenges/ChallengesListScreenView.swift
  Fiero/Views/Challenges/Quick/Details/ChallengeDetailsView.swift
  Fiero/Views/Challenges/Quick/Ongoing/OngoingScreen.swift
  Fiero/Views/Challenges/Quick/QCCategorySelectionView.swift
  Fiero/Views/DesignSystem/Components/Button/ButtonComponent.swift
  Fiero/Views/DesignSystem/Components/ScoreControllers/Duel/DuelScoreComponent.swift
  Fiero/Views/DesignSystem/Components/ScoreControllers/ScoreController3-4/ScoreController3-4Component.swift
Labels: Feature ✨

#307 Feature/tk51and52 haptics and sound toggles
  Fiero.xcodeproj/project.pbxproj
  Fiero/App/FieroApp.swift
  Fiero/Players/HapticsController.swift
  Fiero/Players/SoundPlayer.swift
  Fiero/Views/Profile/ProfileView.swift
  Fiero/Views/Profile/SettingsView.swift
  en.lproj/Localizable.strings
  pt-BR.lproj/Localizable.strings
Labels: Feature ✨, UI 🎨

#330 fix: refact json for online challenges
  Fiero/ViewModel/QuickChallengeViewModel.swift
Labels: Feature ✨, Back-end ⚙️, Combine 🪖

#329 Feature/TK 31 Develop Enter In Challenge By Invitation Code View
  Fiero.xcodeproj/project.pbxproj
  Fiero/Views/Challenges/EnterWithCodeView.swift
  en.lproj/Localizable.strings
  pt-BR.lproj/Localizable.strings
Labels: Feature ✨, UI 🎨

#331 Feature/TK 14 Develop Invitation Code View
  Fiero.xcodeproj/project.pbxproj
  Fiero/Views/Challenges/Quick/Details/InviteChallengerView.swift
  en.lproj/Localizable.strings
  pt-BR.lproj/Localizable.strings
Labels: Feature ✨, UI 🎨

#333 feat: refactor challengeListView
  Fiero/Views/Challenges/ChallengesListScreenView.swift
  Fiero/Views/Challenges/EmptyChallengesView.swift
  en.lproj/Localizable.strings
  pt-BR.lproj/Localizable.strings
Labels: Feature ✨, UI 🎨, Improvements ❤️‍🩹, Refactoring 🔧

#332 Tk9 develop online challenge details view
  Fiero.xcodeproj/project.pbxproj
  Fiero/Assets/Assets.xcassets/OnlineDetails.imageset/Contents.json
  Fiero/Assets/Assets.xcassets/OnlineDetails.imageset/OnlineDetails.png
  Fiero/Assets/Assets.xcassets/OnlineDetails.imageset/OnlineDetails@2x.png
  Fiero/Assets/Assets.xcassets/OnlineDetails.imageset/OnlineDetails@3x.png
  Fiero/Views/Challenges/Quick/Details/OnlineDetails/OnlineChallengeDetailsView.swift
  Fiero/Views/Challenges/Quick/Details/OnlineDetails/ParticipantsList.swift
  en.lproj/Localizable.strings
  pt-BR.lproj/Localizable.strings
Labels: Feature ✨, UI 🎨, Improvements ❤️‍🩹

#328 Feature/TK1 Develop Online or Offline Type Challenge View
  Fiero.xcodeproj/project.pbxproj
  Fiero/Views/Challenges/Quick/Amount/QCAmountWinRulesView.swift
  Fiero/Views/Challenges/Quick/OnlineOrOfflineView/CreationSmallCardStyles.swift
  Fiero/Views/Challenges/Quick/OnlineOrOfflineView/CreationSmallCardView.swift
  Fiero/Views/Challenges/Quick/OnlineOrOfflineView/OnlineOrOfflineView.swift
  Fiero/Views/Challenges/Quick/QCCategorySelectionView.swift
  Fiero/Views/Challenges/Quick/QCNamingView.swift
  Fiero/Views/Challenges/Quick/QCSelectParticipantsView.swift
  Fiero/Views/Challenges/WIP/BestOf/BestOfChallengeWinRulesView.swift
  Fiero/Views/Challenges/WIP/Time/TimeChallengeWinRulesView.swift
  Fiero/Views/Challenges/WIP/Time/TimePickerSelectionView.swift
  Fiero/Views/DesignSystem/Components/Card/ChallengeParticipantsSelectionCardView.swift
  Fiero/Views/DesignSystem/Components/ProgressBar/CustomProgressBar.swift
  en.lproj/Localizable.strings
  pt-BR.lproj/Localizable.strings
Labels: Feature ✨, UI 🎨

#334 Feature/tk40 develop enter challenge by invitation code
  Fiero.xcodeproj/project.pbxproj
  Fiero/AuthTokenService.swift
  Fiero/Extensions/Enums/FieroAPI.swift
  Fiero/Extensions/Enums/JoinChallengeAlertCasesEnum.swift
  Fiero/Players/HapticsController.swift
  Fiero/Players/SoundPlayer.swift
  Fiero/ViewModel/QuickChallengeViewModel.swift
  Fiero/Views/TabBar.swift
Labels: Feature ✨, Back-end ⚙️, Combine 🪖, Refactoring 🔧

#335 Win Screen Appears More than Once
  Fiero/Views/Challenges/Quick/Ongoing/OngoingScreen.swift
Labels: bugfix 🧯, UI 🎨, Improvements ❤️‍🩹

#336 Feature/tk41 develop front back integration to enter challenge by invitation code
  Fiero/Extensions/Enums/JoinChallengeAlertCasesEnum.swift
  Fiero/ViewModel/QuickChallengeViewModel.swift
  Fiero/Views/Challenges/EnterWithCodeView.swift
  Fiero/Views/TabBar.swift
  en.lproj/Localizable.strings
  pt-BR.lproj/Localizable.strings
Labels: Feature ✨, UI 🎨, Back-end ⚙️, Combine 🪖

#338 Feature/tk13 develop front end integration for challenge invitation screen
  Fiero/QuickChallenge.swift
  Fiero/Views/Challenges/ChallengesListScreenView.swift
  Fiero/Views/Challenges/EnterWithCodeView.swift
Labels: Feature ✨, UI 🎨

#340 Move buttons to SettingsView
  Fiero/Views/Profile/ProfileView.swift
  Fiero/Views/Profile/SettingsView.swift
Labels: UI 🎨, Improvements ❤️‍🩹

#339 Tags Challenge List Cell
  Fiero/Views/Challenges/Quick/Details/ChallengeListCell.swift
  Fiero/Views/DesignSystem/Tokens.swift
  en.lproj/Localizable.strings
  pt-BR.lproj/Localizable.strings
Labels: Feature ✨, UI 🎨

#341 Feature/ TK 36 Develop Front-end Integration to Challenge Details When Entering Online Challenges
  Fiero/Views/Challenges/ChallengesListScreenView.swift
  Fiero/Views/Challenges/EmptyChallengesView.swift
  Fiero/Views/Challenges/EnterWithCodeView.swift
  Fiero/Views/Challenges/Quick/Amount/QCAmountWinRulesView.swift
  Fiero/Views/Challenges/Quick/Details/ChallengeDetailsView.swift
  Fiero/Views/Challenges/Quick/Details/InviteChallengerView.swift
  Fiero/Views/Challenges/Quick/Details/OnlineDetails/OnlineChallengeDetailsView.swift
  Fiero/Views/Challenges/Quick/Details/OnlineDetails/ParticipantsList.swift
  Fiero/Views/Challenges/Quick/Ongoing/OngoingScreen.swift
  Fiero/Views/Challenges/Quick/Ongoing/PauseScreen.swift
  Fiero/Views/Challenges/Quick/Ongoing/WinScreen.swift
  Fiero/Views/Challenges/Quick/OnlineOrOfflineView/OnlineOrOfflineView.swift
  Fiero/Views/Challenges/Quick/QCCategorySelectionView.swift
  Fiero/Views/Challenges/Quick/QCChallengeCreatedView.swift
  Fiero/Views/Challenges/Quick/QCNamingView.swift
  Fiero/Views/Challenges/Quick/QCSelectParticipantsView.swift
  Fiero/Views/Challenges/WIP/Time/TimePickerSelectionView.swift
  Fiero/Views/Login/AccountLoginView.swift
  Fiero/Views/Login/Recover Password/InputConfirmationCodeView.swift
  Fiero/Views/Login/Recover Password/RecoverPasswordEmailStepView.swift
  Fiero/Views/Login/TermsOfUseSheetView.swift
  Fiero/Views/Profile/SettingsView.swift
  en.lproj/Localizable.strings
  pt-BR.lproj/Localizable.strings
Labels: Feature ✨, UI 🎨, Combine 🪖
