Repository MarinaFX/Fiero, pull requests merged in 2022-11, with the labels that each got.

#365 feat: finish combine get challenge publisher
  Fiero.xcodeproj/project.pbxproj
  Fiero/Extensions/Enums/FieroAPI.swift
  Fiero/Extensions/Enums/GetChallengeAlertCasesEnum.swift
  Fiero/Extensions/Enums/HTTPResponseError.swift
  Fiero/Extensions/URLSession+Extensions.swift
  Fiero/ViewModel/QuickChallengeViewModel.swift
Labels: Feature ✨, Back-end ⚙️, Combine 🪖

#366 feat: finish refact on patch score combine publisher
  Fiero.xcodeproj/project.pbxproj
  Fiero/Extensions/Enums/EditPlayerScoreAlertCasesEnum.swift
  Fiero/Extensions/Enums/HTTPResponseError.swift
  Fiero/Extensions/URLSession+Extensions.swift
  Fiero/ViewModel/QuickChallengeViewModel.swift
Labels: Back-end ⚙️, Improvements ❤️‍🩹, Combine 🪖

#367 Tk 36 develop new screen of join challenge code with qr code generator
  Fiero.xcodeproj/project.pbxproj
  Fiero/Extensions/Binding+Extensions.swift
  Fiero/Extensions/UIDeviceOrientation+Extensions.swift
  Fiero/Info.plist
  Fiero/Views/Challenges/EnterWithCodeView.swift
  Fiero/Views/Challenges/QRCode/QRCodeScanView.swift
  Fiero/Views/Challenges/QRCode/ScanViewController.swift
  Fiero/Views/Challenges/Quick/Details/InviteChallengerView.swift
  Fiero/Views/Challenges/Quick/Details/QRCodeChallengeInviteView.swift
  Fiero/Views/DesignSystem/Components/InviteCodeScreem/LetterComponent.swift
  en.lproj/Localizable.strings
  pt-BR.lproj/Localizable.strings
Labels: UI 🎨, Improvements ❤️‍🩹

#368 Put online details view inside a ScrollView
  Fiero/Views/Challenges/Quick/Details/OnlineDetails/OnlineChallengeDetailsView.swift
Labels: UI 🎨, Improvements ❤️‍🩹

#369 feat: finish combine publisher to exit challenge
  Fiero.xcodeproj/project.pbxproj
  Fiero/Extensions/Enums/ExitChallengeAlertCasesEnum.swift
  Fiero/Extensions/Enums/FieroAPI.swift
  Fiero/ViewModel/QuickChallengeViewModel.swift
  Fiero/Views/DesignSystem/Components/InviteCode/LetterComponent.swift
  Fiero/Views/DesignSystem/Components/ProfilePictureComponent/ProfilePictureComponent.swift
Labels: Feature ✨, Back-end ⚙️, Combine 🪖

#371 new onboarding texts
  Fiero.xcodeproj/project.pbxproj
  Fiero/Assets/Assets.xcassets/Onboarding/English/OnboardingNameENG.imageset/Contents.json
  Fiero/Assets/Assets.xcassets/Onboarding/English/OnboardingNameENG.imageset/OnboardingNameENG.png
  Fiero/Assets/Assets.xcassets/Onboarding/English/OnboardingNameENG.imageset/Phone Clay Mockup.png
  Fiero/Extensions/Binding+Extensions.swift
  Fiero/Extensions/Enums/EditPlayerScoreAlertCasesEnum.swift
  Fiero/Extensions/Enums/ExitChallengeAlertCasesEnum.swift
  Fiero/Extensions/Enums/FieroAPI.swift
  Fiero/Extensions/Enums/GetChallengeAlertCasesEnum.swift
  Fiero/Extensions/Enums/HTTPResponseError.swift
  Fiero/Extensions/UIDeviceOrientation+Extensions.swift
  Fiero/Extensions/URLSession+Extensions.swift
  Fiero/Info.plist
  Fiero/ViewModel/QuickChallengeViewModel.swift
  Fiero/Views/Challenges/EnterWithCodeView.swift
  Fiero/Views/Challenges/QRCode/QRCodeScanView.swift
  Fiero/Views/Challenges/QRCode/ScanViewController.swift
  Fiero/Views/Challenges/Quick/Details/InviteChallengerView.swift
  Fiero/Views/Challenges/Quick/Details/OnlineDetails/OnlineChallengeDetailsView.swift
  Fiero/Views/Challenges/Quick/Details/QRCodeChallengeInviteView.swift
  Fiero/Views/DesignSystem/Components/InviteCode/LetterComponent.swift
  Fiero/Views/DesignSystem/Components/ProfilePictureComponent/ProfilePictureComponent.swift
  en.lproj/Localizable.strings
  pt-BR.lproj/Localizable.strings
Labels: UI 🎨

#373 Develop Leaderboard Component
  Fiero.xcodeproj/project.pbxproj
  Fiero/Views/DesignSystem/Components/ScoreList/ScoreList.swift
  Fiero/Views/DesignSystem/Components/ScoreList/ScoreListStyle.swift
Labels: Feature ✨, UI 🎨

#372 feat: component finished
  Fiero.xcodeproj/project.pbxproj
  Fiero/Views/DesignSystem/Components/Online/LeaderboardView.swift
Labels: UI 🎨

#374 Improvement | TK 19 Develop Refactoring Create Flow as Tab Bar Item
  Fiero/Views/Challenges/Quick/OnlineOrOfflineView/OnlineOrOfflineView.swift
  Fiero/Views/Challenges/Quick/QCCategorySelectionView.swift
  Fiero/Views/Challenges/Quick/QCChallengeCreatedView.swift
  Fiero/Views/TabBar.swift
  en.lproj/Localizable.strings
  pt-BR.lproj/Localizable.strings
Labels: UI 🎨, Improvements ❤️‍🩹, Refactoring 🔧

#375 Feature/tk3 detail screen participant or owner
  Fiero/Views/Challenges/Quick/Details/ChallengeDetailsView.swift
  Fiero/Views/Challenges/Quick/Details/OnlineDetails/OnlineChallengeDetailsView.swift
Labels: Feature ✨, UI 🎨, Combine 🪖, Hotfix 🚨

#379 Feature/tk4 develop front end online ongoing screen
  Fiero.xcodeproj/project.pbxproj
  Fiero/QuickChallenge.swift
  Fiero/Team.swift
  Fiero/Views/Challenges/Quick/Details/OnlineDetails/OnlineChallengeDetailsView.swift
  Fiero/Views/Challenges/Quick/Ongoing/Online/OnlineOngoingChallengeView.swift
  Fiero/Views/DesignSystem/Components/Online/LeaderboardView.swift
  Fiero/Views/DesignSystem/Components/ScoreList/ScoreList.swift
Labels: Feature ✨, UI 🎨, Back-end ⚙️, Combine 🪖

#383 Feature/tk99 score integration
  Fiero.xcodeproj/project.pbxproj
  Fiero/Extensions/Enums/ExitChallengeAlertCasesEnum.swift
  Fiero/Extensions/Enums/FieroAPI.swift
  Fiero/Extensions/Enums/RemovePlayerAlertCasesEnum.swift
  Fiero/QuickChallenge.swift
  Fiero/ViewModel/QuickChallengeViewModel.swift
  Fiero/Views/Challenges/ChallengesListScreenView.swift
  Fiero/Views/Challenges/EmptyChallengesView.swift
  Fiero/Views/Challenges/EnterWithCodeView.swift
  Fiero/Views/Challenges/QRCode/ScanViewController.swift
  Fiero/Views/Challenges/Quick/Details/OnlineDetails/OnlineChallengeDetailsView.swift
  Fiero/Views/Challenges/Quick/Details/OnlineDetails/ParticipantsList.swift
  Fiero/Views/Challenges/Quick/Ongoing/Online/OnlineOngoingChallengeView.swift
  Fiero/Views/Challenges/Quick/QCCategorySelectionView.swift
  Fiero/Views/DesignSystem/Components/Online/LeaderboardView.swift
  Fiero/Views/DesignSystem/Components/ScoreList/ScoreList.swift
  en.lproj/Localizable.strings
  pt-BR.lproj/Localizable.strings
Labels: Feature ✨, UI 🎨, Back-end ⚙️, Accessibility ♥️, Combine 🪖, Major Changes ☢️

#376 fix: refactor profile and settings
  Fiero/Extensions/Enums/FieroAPI.swift
  Fiero/Views/Challenges/ChallengesListScreenView.swift
  Fiero/Views/Profile/ProfileView.swift
  Fiero/Views/Profile/SettingsView.swift
  en.lproj/Localizable.strings
  pt-BR.lproj/Localizable.strings
Labels: UI 🎨, Refactoring 🔧

#377 fix: change textfield to textview on creation flow
  Fiero.xcodeproj/project.pbxproj
  Fiero/Views/Challenges/Quick/Amount/QCAmountWinRulesView.swift
  Fiero/Views/Challenges/Quick/QCNamingView.swift
  Fiero/Views/DesignSystem/Components/TextViews/CreationFlowTextViewComponent.swift
  Fiero/Views/DesignSystem/Components/TextViews/CreationFlowTextViewStyles.swift
Labels: UI 🎨, Improvements ❤️‍🩹

#378 feat: make cards clickable (online/offline and number of participants cards)
  Fiero/Extensions/Enums/FieroAPI.swift
  Fiero/Views/Challenges/ChallengesListScreenView.swift
  Fiero/Views/Challenges/Quick/OnlineOrOfflineView/OnlineOrOfflineView.swift
  Fiero/Views/Challenges/Quick/QCNamingView.swift
  Fiero/Views/Challenges/Quick/QCSelectParticipantsView.swift
Labels: UI 🎨, Improvements ❤️‍🩹

#386 Alerta de logout ta sem texto
  Fiero/Views/Profile/SettingsView.swift
  en.lproj/Localizable.strings
  pt-BR.lproj/Localizable.strings
Labels: UI 🎨

#390 fix: adjust localizables on onboarding, online details and challenge created screen
  Fiero/Assets/Assets.xcassets/Onboarding/English/OnboardingNameENG.imageset/OnboardingNameENG.png
  Fiero/Views/Challenges/Quick/Details/OnlineDetails/OnlineChallengeDetailsView.swift
  Fiero/Views/Challenges/Quick/QCChallengeCreatedView.swift
  en.lproj/Localizable.strings
  pt-BR.lproj/Localizable.strings
Labels: UI 🎨, Accessibility ♥️

#392 Feature/tk health kit creation flow and ongoing
  Fiero.xcodeproj/project.pbxproj
  Fiero/Views/Challenges/Quick/QCCategorySelectionView.swift
  Fiero/Views/Challenges/Quick/QCNamingView.swift
  Fiero/Views/DesignSystem/Components/Card/CategoryView/CardCategoryStyles.swift
  Fiero/Views/DesignSystem/Components/Card/CategoryView/ChallengeCategoryCardView.swift
  en.lproj/Localizable.strings
  pt-BR.lproj/Localizable.strings
Labels: Feature ✨, UI 🎨

#393 Improvements/tk999 adjust app accessibility
  Fiero.xcodeproj/project.pbxproj
  Fiero/Info.plist
  Fiero/Lottie/steps.json
  Fiero/ViewModel/QuickChallengeViewModel.swift
  Fiero/Views/Challenges/EmptyChallengesView.swift
  Fiero/Views/Challenges/Quick/Amount/QCAmountWinRulesView.swift
  Fiero/Views/Challenges/Quick/Details/ChallengeListCell.swift
  Fiero/Views/Challenges/Quick/Details/InviteChallengerView.swift
  Fiero/Views/Challenges/Quick/Details/OnlineDetails/OnlineChallengeDetailsView.swift
  Fiero/Views/Challenges/Quick/Details/OnlineDetails/ParticipantsList.swift
  Fiero/Views/Challenges/Quick/Ongoing/OngoingScreen.swift
  Fiero/Views/Challenges/Quick/OnlineOrOfflineView/OnlineOrOfflineView.swift
  Fiero/Views/Challenges/Quick/QCCategorySelectionView.swift
  Fiero/Views/Challenges/Quick/QCChallengeCreatedView.swift
  Fiero/Views/Challenges/Quick/QCNamingView.swift
  Fiero/Views/DesignSystem/Components/Button/ButtonComponent.swift
  Fiero/Views/DesignSystem/Components/Card/CategoryView/ChallengeCategoryCardView.swift
  Fiero/Views/DesignSystem/Components/Checkbox/CheckboxComponent.swift
  Fiero/Views/DesignSystem/Components/InviteCode/LetterComponent.swift
  Fiero/Views/DesignSystem/Components/Online/LeaderboardView.swift
  Fiero/Views/DesignSystem/Components/ScoreControllers/ScoreController3-4/ScoreController3-4Component.swift
  Fiero/Views/DesignSystem/Components/ScoreList/ScoreList.swift
  Fiero/Views/Login/AccountLoginView.swift
  Fiero/Views/Login/Onboarding/OnboardingCard.swift
  Fiero/Views/Login/Recover Password/InputConfirmationCodeView.swift
  Fiero/Views/Login/Recover Password/RecoverPasswordEmailStepView.swift
  Fiero/Views/Profile/ProfileBodyTextView.swift
  Fiero/Views/Profile/ProfileView.swift
  en.lproj/Localizable.strings
  pt-BR.lproj/Localizable.strings
Labels: UI 🎨, Improvements ❤️‍🩹, Accessibility ♥️
