Repository MarinaFX/Fiero, pull requests merged in 2022-07, with the labels that each got.

#1 Feature/setting test pipeline
  .github/workflows/test_pipeline.yml
  Fiero.xcodeproj/project.pbxproj
  FieroTests/FieroTests.swift
  docs/pull_request_template.md
Labels: Feature, Back-end, Tests

#11 Dev
  .github/workflows/test_pipeline.yml
  Fiero.xcodeproj/project.pbxproj
  FieroTests/FieroTests.swift
  docs/pull_request_template.md
Labels: Feature, Back-end, Tests

#12 Staging
  .github/workflows/test_pipeline.yml
  Fiero.xcodeproj/project.pbxproj
  FieroTests/FieroTests.swift
Labels: Feature, Back-end, Tests

#2 creating codeowners file
  .github/CODEOWNERS
Labels: documentation, Feature

#14 Dev
  Fiero.xcodeproj/project.pbxproj
  Fiero/Views/DesignSystem/Tokens.swift
Labels: Feature, UI

#15 Staging
  Fiero.xcodeproj/project.pbxproj
  Fiero/Views/DesignSystem/Tokens.swift
Labels: Feature, UI, Tests

#18 Feature/tk25 develop account login screen components
  Fiero.xcodeproj/project.pbxproj
  Fiero.xcodeproj/xcuserdata/illuminaty.xcuserdatad/xcschemes/xcschememanagement.plist
  Fiero/Views/DesignSystem/Components/ButtonComponent.swift
  Fiero/Views/DesignSystem/Components/ButtonStyles.swift
Labels: Feature, UI, WIP

#19 Staging changes
  Fiero.xcodeproj/project.pbxproj
  Fiero.xcodeproj/xcuserdata/illuminaty.xcuserdatad/xcschemes/xcschememanagement.plist
  Fiero/Views/DesignSystem/Components/ButtonComponent.swift
  Fiero/Views/DesignSystem/Components/ButtonStyles.swift
Labels: Feature, UI

#16 Feature/TK26 Develop Account Registration Screen Components
  .github/CODEOWNERS
  Fiero.xcodeproj/project.pbxproj
  Fiero/Assets.xcassets/AppIcon.appiconset/Contents.json
  Fiero/Extensions/View+Extensions.swift
  Fiero/Views/ContentView.swift
  Fiero/Views/DesignSystem/Components/ButtonStyles.swift
  Fiero/Views/DesignSystem/Components/PrimaryTextField.swift
  Fiero/Views/DesignSystem/Tokens.swift
Labels: Feature, UI, WIP

#21 FEATURE/TK60 Develop Alert Component
  Fiero.xcodeproj/project.pbxproj
  Fiero/Views/DesignSystem/Components/Alert/AlertComponent.swift
  Fiero/Views/DesignSystem/Components/Alert/AlertStyles.swift
Labels: Feature, UI

#24 Staging
  .github/CODEOWNERS
  Fiero.xcodeproj/project.pbxproj
  Fiero/Assets.xcassets/AppIcon.appiconset/Contents.json
  Fiero/Extensions/View+Extensions.swift
  Fiero/Views/ContentView.swift
  Fiero/Views/DesignSystem/Components/Alert/AlertComponent.swift
  Fiero/Views/DesignSystem/Components/Alert/AlertStyles.swift
  Fiero/Views/DesignSystem/Components/ButtonStyles.swift
  Fiero/Views/DesignSystem/Components/PrimaryTextField.swift
  Fiero/Views/DesignSystem/Tokens.swift
Labels: Feature, Tests

#27 Integrating to prod changes developed at #22
  Fiero.xcodeproj/project.pbxproj
  Fiero/Views/ContentView.swift
  Fiero/Views/DesignSystem/Components/CustomTextFieldView.swift
  Fiero/Views/DesignSystem/Components/PrimaryTextField.swift
  Fiero/Views/DesignSystem/Components/SecurePrimaryTextField.swift
  Fiero/Views/DesignSystem/Enums/TextFieldStyleVariant.swift
Labels: Feature

#28 Feature/TK61 Develop Checkbox Component
  Fiero.xcodeproj/project.pbxproj
  Fiero/Views/DesignSystem/Components/Button/ButtonComponent.swift
  Fiero/Views/DesignSystem/Components/Button/ButtonStyles.swift
  Fiero/Views/DesignSystem/Components/Checkbox/CheckboxComponent.swift
  Fiero/Views/DesignSystem/Components/Checkbox/CheckboxStyles.swift
Labels: Feature, bugfix, UI

#29 Staging changes from dev to Staging #28
  Fiero.xcodeproj/project.pbxproj
  Fiero/Views/DesignSystem/Components/Button/ButtonComponent.swift
  Fiero/Views/DesignSystem/Components/Button/ButtonStyles.swift
  Fiero/Views/DesignSystem/Components/Checkbox/CheckboxComponent.swift
  Fiero/Views/DesignSystem/Components/Checkbox/CheckboxStyles.swift
Labels: Feature, UI

#30 Staging changes from Staging to prod #28
  Fiero.xcodeproj/project.pbxproj
  Fiero/Views/DesignSystem/Components/Button/ButtonComponent.swift
  Fiero/Views/DesignSystem/Components/Button/ButtonStyles.swift
  Fiero/Views/DesignSystem/Components/Checkbox/CheckboxComponent.swift
  Fiero/Views/DesignSystem/Components/Checkbox/CheckboxStyles.swift
Labels: Feature, UI, Tests

#31 Feature/TK 31 Develop Account Registration Screen
  Fiero.xcodeproj/project.pbxproj
  Fiero/Assets.xcassets/LoginBackground.imageset/Contents.json
  Fiero/Assets.xcassets/LoginBackground.imageset/LoginBackground.png
  Fiero/Assets.xcassets/LoginBackground.imageset/LoginBackground@2x.png
  Fiero/Assets.xcassets/LoginBackground.imageset/LoginBackground@3x.png
  Fiero/Views/ContentView.swift
  Fiero/Views/DesignSystem/Components/Button/ButtonComponent.swift
  Fiero/Views/DesignSystem/Components/Checkbox/CheckboxComponent.swift
  Fiero/Views/RegistrationScreen.swift
Labels: Feature, UI

#34 Dev
  Fiero.xcodeproj/project.pbxproj
  Fiero/Assets.xcassets/LoginBackground.imageset/Contents.json
  Fiero/Assets.xcassets/LoginBackground.imageset/LoginBackground.png
  Fiero/Assets.xcassets/LoginBackground.imageset/LoginBackground@2x.png
  Fiero/Assets.xcassets/LoginBackground.imageset/LoginBackground@3x.png
  Fiero/Views/ContentView.swift
  Fiero/Views/DesignSystem/Components/Button/ButtonComponent.swift
  Fiero/Views/DesignSystem/Components/Checkbox/CheckboxComponent.swift
  Fiero/Views/RegistrationScreen.swift
Labels: Feature, UI

#33 Bugfix/TK69 Fix checkbox behavior
  Fiero/Views/DesignSystem/Components/Checkbox/CheckboxComponent.swift
  Fiero/Views/DesignSystem/Components/Checkbox/CheckboxStyles.swift
  Fiero/Views/RegistrationScreen.swift
Labels: bugfix

#36 Ready for testing
  Fiero/Views/DesignSystem/Components/Checkbox/CheckboxComponent.swift
  Fiero/Views/DesignSystem/Components/Checkbox/CheckboxStyles.swift
  Fiero/Views/RegistrationScreen.swift
Labels: Feature, UI

#37 Staging
  Fiero/Views/DesignSystem/Components/Checkbox/CheckboxComponent.swift
  Fiero/Views/DesignSystem/Components/Checkbox/CheckboxStyles.swift
  Fiero/Views/RegistrationScreen.swift
Labels: Feature, UI, Tests

#38 Feature/TK30 Develop Account Login Screen
  Fiero.xcodeproj/project.pbxproj
  Fiero/Assets.xcassets/LoginBackground.imageset/Contents.json
  Fiero/Assets.xcassets/LoginBackground.imageset/Screen-image.png
  Fiero/Assets.xcassets/LoginBackground.imageset/Screen-image@2x.png
  Fiero/Assets.xcassets/LoginBackground.imageset/Screen-image@3x.png
  Fiero/Views/ContentView.swift
  Fiero/Views/DesignSystem/Components/Button/ButtonComponent.swift
  Fiero/Views/DesignSystem/Components/Button/ButtonStyles.swift
  Fiero/Views/DesignSystem/Components/SecurePrimaryTextField.swift
  Fiero/Views/DesignSystem/Components/TextFields/CustomTextFieldView.swift
  Fiero/Views/DesignSystem/Components/TextFields/PrimaryTextFieldStyle.swift
  Fiero/Views/DesignSystem/Tokens.swift
  Fiero/Views/Login/AccountLoginView.swift
  Fiero/Views/Login/RegistrationScreenView.swift
Labels: Feature, UI

#42 Improvement/TK71 Improvement Dynamic Types on Fonts
  Fiero.xcodeproj/project.pbxproj
  Fiero/Views/DesignSystem/Components/Alert/AlertComponent.swift
  Fiero/Views/DesignSystem/Components/Alert/AlertStyles.swift
  Fiero/Views/DesignSystem/Components/Button/ButtonComponent.swift
  Fiero/Views/DesignSystem/Components/Button/ButtonStyles.swift
  Fiero/Views/DesignSystem/Components/Checkbox/CheckboxComponent.swift
  Fiero/Views/DesignSystem/Components/Checkbox/CheckboxStyles.swift
  Fiero/Views/DesignSystem/Components/TextFields/CustomTextFieldView.swift
  Fiero/Views/DesignSystem/Components/TextFields/PrimaryTextFieldStyle.swift
  Fiero/Views/DesignSystem/Tokens.swift
  Fiero/Views/Login/AccountLoginView.swift
  Fiero/Views/Login/RegistrationScreenView.swift
Labels: UI, Improvements

#73 Feature/TK 66 Develop Login Integration With Api
  Fiero.xcodeproj/project.pbxproj
  Fiero.xcodeproj/xcuserdata/marinadepazzi.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  Fiero/App/FieroApp.swift
  Fiero/Assets/Assets.xcassets/AccentColor.colorset/Contents.json
  Fiero/Assets/Assets.xcassets/AppIcon.appiconset/Contents.json
  Fiero/Assets/Assets.xcassets/Contents.json
  Fiero/Assets/Assets.xcassets/LoginBackground.imageset/Contents.json
  Fiero/Assets/Assets.xcassets/LoginBackground.imageset/LoginBackground.png
  Fiero/Assets/Assets.xcassets/LoginBackground.imageset/LoginBackground@2x.png
  Fiero/Assets/Assets.xcassets/LoginBackground.imageset/LoginBackground@3x.png
  Fiero/Assets/Assets.xcassets/LoginBackground.imageset/Screen-image.png
  Fiero/Assets/Assets.xcassets/LoginBackground.imageset/Screen-image@2x.png
  Fiero/Assets/Assets.xcassets/LoginBackground.imageset/Screen-image@3x.png
  Fiero/User.swift
  Fiero/UserResponse.swift
  Fiero/ViewModel/UserLoginViewModel.swift
  Fiero/ViewModel/UserRegistrationViewModel.swift
  Fiero/Views/ContentView.swift
  Fiero/Views/Login/AccountLoginView.swift
  Fiero/Views/Login/RegistrationScreenView.swift
Labels: Feature, UI, Back-end

#74 Improvement/TK26 Develop Checkbox Component Text to be Clickable
  Fiero/Views/DesignSystem/Components/Checkbox/CheckboxComponent.swift
  Fiero/Views/Login/RegistrationScreenView.swift
Labels: UI, Improvements

#78 fix: BlurBoxHeigthRegistration
  Fiero.xcodeproj/project.pbxproj
  Fiero/App/FieroApp.swift
  Fiero/Views/Login/AccountLoginView.swift
  Fiero/Views/Login/RegistrationScreenView.swift
Labels: bugfix, UI

#79 Feature/TK25 Develop Terms of Use Sheet View on Registration Screen
  Fiero.xcodeproj/project.pbxproj
  Fiero/Views/DesignSystem/Components/Button/ButtonComponent.swift
  Fiero/Views/DesignSystem/Components/Button/ButtonStyles.swift
  Fiero/Views/DesignSystem/Components/Checkbox/CheckboxComponent.swift
  Fiero/Views/Login/RegistrationScreenView.swift
  Fiero/Views/Login/TermsOfUseSheetView.swift
Labels: Feature

#81 Bug/tk60 fix text field placeholder color
  Fiero/Views/DesignSystem/Components/TextFields/CustomTextFieldView.swift
  Fiero/Views/Login/AccountLoginView.swift
  Fiero/Views/Login/RegistrationScreenView.swift
Labels: bug, Feature, bugfix, UI

#84 feat: RoundScoreCompoment
  Fiero.xcodeproj/project.pbxproj
  Fiero/Views/DesignSystem/Components/List/RoundScore/RoundScoreComponent.swift
  Fiero/Views/DesignSystem/Components/List/RoundScore/RoundScoreStyle.swift
Labels: Feature, UI

#82 Improvement/TK23 Develop Support to Dynamic Types on Registration Screen
  Fiero/Assets/Assets.xcassets/LoginBackgroundDynamicType.imageset/Contents.json
  Fiero/Assets/Assets.xcassets/LoginBackgroundDynamicType.imageset/image 9.png
  Fiero/Views/Login/RegistrationScreenView.swift
  Fiero/Views/Login/TermsOfUseSheetView.swift
Labels: bugfix, UI, Improvements

#83 Improvement/TK68 Implement Unit Testing on Login Authentication
  Fiero.xcodeproj/project.pbxproj
  Fiero/Assets/Assets.xcassets/LoginBackground.imageset/Contents.json
  Fiero/Assets/Assets.xcassets/LoginBackground.imageset/Screen-image.png
  Fiero/Assets/Assets.xcassets/LoginBackground.imageset/Screen-image@2x.png
  Fiero/Assets/Assets.xcassets/LoginBackground.imageset/Screen-image@3x.png
  Fiero/Extensions/Enums/HTTPResult.swift
  Fiero/Extensions/Enums/ServerResponse.swift
  Fiero/Extensions/HTTPClient.swift
  Fiero/Extensions/Publisher+Extensions.swift
  Fiero/Extensions/URLSession+Extensions.swift
  Fiero/User.swift
  Fiero/UserResponse.swift
  Fiero/ViewModel/UserLoginViewModel.swift
  Fiero/ViewModel/UserRegistrationViewModel.swift
  Fiero/Views/ContentView.swift
  Fiero/Views/Login/RegistrationScreenView.swift
  FieroTests/FieroTests.swift
  FieroTests/Login+Registration/UserLoginViewModelTests.swift
  FieroTests/Login+Registration/UserRegistrationViewModelTests.swift
  FieroTests/MockHTTPClient.swift
Labels: Back-end, Improvements, Tests

#85 Improvement/TK24 Develop support to Dynamic Types on Login Screen
  Fiero/Views/DesignSystem/Components/Button/ButtonComponent.swift
  Fiero/Views/DesignSystem/Components/Checkbox/CheckboxComponent.swift
  Fiero/Views/Login/AccountLoginView.swift
Labels: documentation, UI, Improvements

#87 Dev
  Fiero.xcodeproj/project.pbxproj
  Fiero/App/FieroApp.swift
  Fiero/Assets/Assets.xcassets/LoginBackground.imageset/Contents.json
  Fiero/Assets/Assets.xcassets/LoginBackground.imageset/Screen-image.png
  Fiero/Assets/Assets.xcassets/LoginBackground.imageset/Screen-image@2x.png
  Fiero/Assets/Assets.xcassets/LoginBackground.imageset/Screen-image@3x.png
  Fiero/Assets/Assets.xcassets/LoginBackgroundDynamicType.imageset/Contents.json
  Fiero/Assets/Assets.xcassets/LoginBackgroundDynamicType.imageset/image 9.png
  Fiero/Extensions/Enums/HTTPResult.swift
  Fiero/Extensions/Enums/ServerResponse.swift
  Fiero/Extensions/HTTPClient.swift
  Fiero/Extensions/Publisher+Extensions.swift
  Fiero/Extensions/URLSession+Extensions.swift
  Fiero/User.swift
  Fiero/UserResponse.swift
  Fiero/ViewModel/UserLoginViewModel.swift
  Fiero/ViewModel/UserRegistrationViewModel.swift
  Fiero/Views/DesignSystem/Components/Button/ButtonComponent.swift
  Fiero/Views/DesignSystem/Components/Button/ButtonStyles.swift
  Fiero/Views/DesignSystem/Components/Checkbox/CheckboxComponent.swift
  Fiero/Views/DesignSystem/Components/List/RoundScore/RoundScoreComponent.swift
  Fiero/Views/DesignSystem/Components/List/RoundScore/RoundScoreStyle.swift
  Fiero/Views/DesignSystem/Components/TextFields/CustomTextFieldView.swift
  Fiero/Views/Login/AccountLoginView.swift
  Fiero/Views/Login/RegistrationScreenView.swift
  Fiero/Views/Login/TermsOfUseSheetView.swift
  FieroTests/FieroTests.swift
  FieroTests/Login+Registration/UserLoginViewModelTests.swift
  FieroTests/Login+Registration/UserRegistrationViewModelTests.swift
  FieroTests/MockHTTPClient.swift
Labels: Feature, UI, Back-end

#91 Feature/TK71 Develop ChallengesTypeCell Component - List
  Fiero.xcodeproj/project.pbxproj
  Fiero/Views/DesignSystem/Components/List/ChallengeTypes/BestOfComponent.swift
  Fiero/Views/DesignSystem/Components/List/ChallengeTypes/QuantityTimeComponent.swift
  Fiero/Views/DesignSystem/Components/List/ChallengeTypes/QuantityTimeStyles.swift
  Fiero/Views/DesignSystem/Tokens.swift
Labels: Feature, UI

#90 LoginScreen Flow To Registration
  Fiero/Views/Login/AccountLoginView.swift
  Fiero/Views/Login/RegistrationScreenView.swift
Labels: Improvements

#93 Cell List Component
  Fiero.xcodeproj/project.pbxproj
  Fiero/Views/DesignSystem/Components/List/ChallengeCell/ChallengeCellComponent.swift
  Fiero/Views/DesignSystem/Components/List/ChallengeCell/ChallengeCellStyle.swift
Labels: Feature, UI
