Repository MarinaFX/Fiero, pull requests merged in 2022-09, with the labels that each got.

#224 change color of token on DS
  Fiero/Views/DesignSystem/Tokens.swift
Labels: UI 🎨

#228 Tk9 loading feedback on login signup screen
  Fiero.xcodeproj/project.pbxproj
  Fiero/Lottie.swift
  Fiero/Lottie/animation.geojson
  Fiero/Lottie/animation.json
  Fiero/Lottie/blockCategory.json
  Fiero/Lottie/loading.json
  Fiero/Lottie/quantity.json
  Fiero/Lottie/quantity2.json
  Fiero/Lottie/tonto.json
  Fiero/Member.swift
  Fiero/Views/Challenges/EmptyChallengesView.swift
  Fiero/Views/Challenges/Quick/Details/ChallengeDetailsView.swift
  Fiero/Views/Challenges/Quick/Ongoing/OngoingDuelScreenView.swift
  Fiero/Views/Challenges/Quick/QCCategorySelectionView.swift
  Fiero/Views/DesignSystem/Components/Card/ChallengeCategoryCardView.swift
  Fiero/Views/DesignSystem/Tokens.swift
  Fiero/Views/Login/AccountLoginView.swift
  Fiero/Views/Login/RegistrationScreenView.swift
  Fiero/Views/TabBar.swift
Labels: UI 🎨

#229 Improvement/TK24 Lateral hint for next cards on create challenge
  Fiero.xcodeproj/project.pbxproj
  Fiero/Views/Challenges/Quick/QCCategorySelectionView.swift
  Fiero/Views/Challenges/Quick/ScrollingModifier.swift
  Fiero/Views/DesignSystem/Components/Card/ChallengeCategoryCardView.swift
Labels: UI 🎨, Improvements ❤️‍🩹

#230 Tk12 rethink all app text strings
  Fiero/Views/Challenges/ChallengesListScreenView.swift
  Fiero/Views/Challenges/EmptyChallengesView.swift
  Fiero/Views/Challenges/Quick/Amount/QCAmountWinRulesView.swift
  Fiero/Views/Challenges/Quick/Details/ChallengeDetailsView.swift
  Fiero/Views/Challenges/Quick/Ongoing/PauseScreen.swift
  Fiero/Views/Challenges/Quick/QCCategorySelectionView.swift
  Fiero/Views/Challenges/Quick/QCNamingView.swift
  Fiero/Views/Challenges/Quick/QCSelectParticipantsView.swift
  Fiero/Views/DesignSystem/Components/Card/ChallengeCategoryCardView.swift
  Fiero/Views/DesignSystem/Tokens.swift
  Fiero/Views/Login/LoginAlertCases.swift
  Fiero/Views/Login/RegistrationAlertCases.swift
  Fiero/Views/Profile/ProfileView.swift
  Fiero/Views/TabBar.swift
Labels: UI 🎨, Improvements ❤️‍🩹

#231 Feature/delete account
  Fiero.xcodeproj/project.pbxproj
  Fiero/Extensions/Enums/UDKeys.swift
  Fiero/User.swift
  Fiero/UserLoginResponse.swift
  Fiero/UserResponse.swift
  Fiero/ViewModel/ProfileViewModel.swift
  Fiero/ViewModel/QuickChallengeViewModel.swift
  Fiero/ViewModel/UserLoginViewModel.swift
  Fiero/ViewModel/UserRegistrationViewModel.swift
  Fiero/ViewModel/UserViewModel.swift
  Fiero/Views/ContentView.swift
  Fiero/Views/Login/AccountLoginView.swift
  Fiero/Views/Login/UserSignupView.swift
  Fiero/Views/Profile/ProfileView.swift
  Fiero/Views/Profile/ProfileViewModel.swift
  FieroTests/Login+Registration/UserRegistrationViewModelTests.swift
Labels: Feature ✨, UI 🎨, Back-end ⚙️, Combine 🪖

#235 BugFix: TK 99 Fix Finish Challenge Button Working
  Fiero/Views/Challenges/Quick/Ongoing/PauseScreen.swift
Labels: bugfix 🧯, UI 🎨

#236 feat: add signup fixes
  Fiero/ViewModel/QuickChallengeViewModel.swift
  Fiero/ViewModel/UserViewModel.swift
Labels: Back-end ⚙️, Combine 🪖

#237 Tk UI improvementes of brenda and marcelo
  Fiero/Views/Challenges/Quick/Ongoing/WinScreen.swift
  Fiero/Views/DesignSystem/Components/Button/ButtonStyles.swift
  Fiero/Views/DesignSystem/Components/Card/ChallengeCategoryCardView.swift
  Fiero/Views/DesignSystem/Components/Scoreboard/Components/GroupComponent.swift
  Fiero/Views/Profile/ProfileView.swift
Labels: UI 🎨, Improvements ❤️‍🩹

#242 Tk42 details screencorrigir fix participant component wit outline instead background color
  Fiero/Views/Challenges/Quick/Details/ChallengeDetailsView.swift
  Fiero/Views/DesignSystem/Components/Scoreboard/Components/GroupComponent.swift
  Fiero/Views/DesignSystem/Components/Scoreboard/Styles/ParticipantStyles.swift
Labels: UI 🎨, Improvements ❤️‍🩹

#243 change label to Fazer Login
  Fiero/Views/Login/AccountLoginView.swift
Labels: UI 🎨

#244 fix text color
  Fiero/Views/Login/TermsOfUseSheetView.swift
Labels: UI 🎨

#245 feat: added alert when saving points is not possible
  Fiero/ViewModel/QuickChallengeViewModel.swift
  Fiero/ViewModel/UserViewModel.swift
  Fiero/Views/Challenges/Quick/Details/ChallengeDetailsView.swift
  Fiero/Views/Challenges/Quick/Details/DetailsAlertCases.swift
  Fiero/Views/Challenges/Quick/Ongoing/DuelScreenView.swift
  Fiero/Views/Challenges/Quick/Ongoing/OngoingDuelScreenView.swift
  Fiero/Views/Challenges/Quick/QCChallengeCreatedView.swift
  Fiero/Views/DesignSystem/Components/ScoreControllers/Duel/DuelScoreComponent.swift
Labels: UI 🎨, Back-end ⚙️, Combine 🪖

#246 BugFix/TK36 Ongoing: Fix Score Long Press
  Fiero/Views/DesignSystem/Components/ScoreControllers/Duel/DuelScoreComponent.swift
  Fiero/Views/DesignSystem/Components/ScoreControllers/ScoreController3-4/ScoreController3-4Component.swift
Labels: bugfix 🧯, UI 🎨

#248 Tk50 implement new cell design on challenge list
  Fiero.xcodeproj/project.pbxproj
  Fiero/Views/Challenges/ChallengesListScreenView.swift
  Fiero/Views/Challenges/Quick/Amount/QCAmountWinRulesView.swift
  Fiero/Views/Challenges/Quick/Details/ChallengeListCell.swift
  Fiero/Views/Login/UserSignupView.swift
Labels: UI 🎨, Improvements ❤️‍🩹

#250 Feature/swipe actions for challenges list
  Fiero/Views/Challenges/ChallengesListScreenView.swift
  Fiero/Views/Challenges/Quick/Details/ChallengeDetailsView.swift
  Fiero/Views/Challenges/Quick/Details/DetailsAlertCases.swift
Labels: UI 🎨

#249 Improvement/TK38 + 40 Ongoing: Change 3 or 4 participants challenge design
  Fiero/Views/Challenges/Quick/Ongoing/Ongoing3_4ScreenView.swift
  Fiero/Views/Challenges/Quick/Ongoing/OngoingDuelScreenView.swift
  Fiero/Views/DesignSystem/Components/ScoreControllers/ScoreController3-4/ScoreController3-4Component.swift
Labels: UI 🎨, Improvements ❤️‍🩹

#251 Improvements/adjust participants component for dynamic types
  Fiero/Views/Challenges/Quick/Details/ChallengeDetailsView.swift
  Fiero/Views/DesignSystem/Components/Scoreboard/Components/GroupComponent.swift
Labels: UI 🎨, Accessibility ♥️

#252 UI Adjustments Home, Create Challenge, Profile, Onboarding
  Fiero.xcodeproj/project.pbxproj
  Fiero/Assets/Assets.xcassets/Onboarding-v2/Contents.json
  Fiero/Assets/Assets.xcassets/Onboarding-v2/Desafie.imageset/Contents.json
  Fiero/Assets/Assets.xcassets/Onboarding-v2/Desafie.imageset/Desafie.png
  Fiero/Assets/Assets.xcassets/Onboarding-v2/Multiplos.imageset/Contents.json
  Fiero/Assets/Assets.xcassets/Onboarding-v2/Multiplos.imageset/Multiplos.png
  Fiero/Assets/Assets.xcassets/Onboarding-v2/Pontuacao.imageset/Contents.json
  Fiero/Assets/Assets.xcassets/Onboarding-v2/Pontuacao.imageset/Pontuacao.png
  Fiero/Lottie/sad.json
  Fiero/Lottie/success-loop.json
  Fiero/Lottie/tonto2.json
  Fiero/Views/Challenges/EmptyChallengesView.swift
  Fiero/Views/Challenges/Quick/QCCategorySelectionView.swift
  Fiero/Views/Challenges/Quick/QCChallengeCreatedView.swift
  Fiero/Views/DesignSystem/Components/Button/ButtonStyles.swift
  Fiero/Views/DesignSystem/Tokens.swift
  Fiero/Views/Login/Onboarding/Onboarding.swift
  Fiero/Views/Login/Onboarding/OnboardingCard.swift
  Fiero/Views/Profile/ProfileView.swift
Labels: Feature ✨, bugfix 🧯, UI 🎨, Improvements ❤️‍🩹

#254 Improvements/tk25 create challenge add start and continuation animation on amount
  Fiero/ViewModel/QuickChallengeViewModel.swift
  Fiero/ViewModel/UserViewModel.swift
  Fiero/Views/DesignSystem/Components/Card/ChallengeCategoryCardView.swift
Labels: UI 🎨, Improvements ❤️‍🩹

#255 fix: play card animation when it is focused
  Fiero.xcodeproj/project.pbxproj
  Fiero/LottieView.swift
  Fiero/Views/Challenges/Quick/QCCategorySelectionView.swift
  Fiero/Views/DesignSystem/Components/Card/CategoryView/CardCategoryStyles.swift
  Fiero/Views/DesignSystem/Components/Card/CategoryView/ChallengeCategoryCardView.swift
Labels: UI 🎨, Improvements ❤️‍🩹

#256 Tk70 add log out button on profile view
  Fiero/ViewModel/UserViewModel.swift
  Fiero/Views/Profile/ProfileView.swift
Labels: UI 🎨, Improvements ❤️‍🩹

#258 Fix Bug Challenge Name
  Fiero/Views/Challenges/Quick/Details/ChallengeDetailsView.swift
  Fiero/Views/DesignSystem/Components/TextFields/PermanentKeyboard.swift
Labels: UI 🎨, Improvements ❤️‍🩹, Accessibility ♥️

#259 feat: fix signup view alert cases
  Fiero/Views/Login/AccountLoginView.swift
  Fiero/Views/Login/SignupAlertCases.swift
  Fiero/Views/Login/UserSignupView.swift
Labels: UI 🎨

#257 Bugfix/segue from created challenge to ongoing challenge
  Fiero.xcodeproj/project.pbxproj
  Fiero/Lottie/quantity-list-cell.json
  Fiero/ViewModel/QuickChallengeViewModel.swift
  Fiero/ViewModel/UserViewModel.swift
  Fiero/Views/Challenges/ChallengesListScreenView.swift
  Fiero/Views/Challenges/Quick/Amount/QCAmountWinRulesView.swift
  Fiero/Views/Challenges/Quick/Details/ChallengeDetailsView.swift
  Fiero/Views/Challenges/Quick/Details/ChallengeListCell.swift
  Fiero/Views/Challenges/Quick/Ongoing/Ongoing3_4ScreenView.swift
  Fiero/Views/Challenges/Quick/QCChallengeCreatedView.swift
  Fiero/Views/Challenges/Quick/QCSelectParticipantsView.swift
  Fiero/Views/ContentView.swift
  Fiero/Views/DesignSystem/Components/Button/ButtonStyles.swift
  Fiero/Views/DesignSystem/Components/ScoreControllers/ScoreController3-4/ScoreController3-4Component.swift
  Fiero/Views/Profile/ProfileView.swift
Labels: UI 🎨, Back-end ⚙️, Improvements ❤️‍🩹, Combine 🪖

#260 feat: add english localization to Fiero
  Fiero.xcodeproj/project.pbxproj
  en.lproj/Localizable.strings
  pt-BR.lproj/Localizable.strings
Labels: Feature ✨, Accessibility ♥️

#261 Feature/TK41 Ongoing: win animation when score reaches the determined in the creation of challenge
  Fiero/Assets/Assets.xcassets/winScreen/Contents.json
  Fiero/Assets/Assets.xcassets/winScreen/bg_winner.imageset/BG.png
  Fiero/Assets/Assets.xcassets/winScreen/bg_winner.imageset/Contents.json
  Fiero/Assets/Assets.xcassets/winScreen/venceu.imageset/Contents.json
  Fiero/Assets/Assets.xcassets/winScreen/venceu.imageset/venceu.png
  Fiero/Assets/Assets.xcassets/winScreen/win.imageset/Contents.json
  Fiero/Assets/Assets.xcassets/winScreen/win.imageset/win.png
  Fiero/Assets/Assets.xcassets/winScreen/winner.imageset/Contents.json
  Fiero/Assets/Assets.xcassets/winScreen/winner.imageset/W I N N E R.png
  Fiero/Assets/Assets.xcassets/youwin-en.imageset/youwin-en.png
  Fiero/Views/Challenges/Quick/Ongoing/Ongoing3_4ScreenView.swift
  Fiero/Views/Challenges/Quick/Ongoing/OngoingDuelScreenView.swift
  Fiero/Views/Challenges/Quick/Ongoing/WinScreen.swift
  Fiero/Views/DesignSystem/Components/ScoreControllers/Duel/DuelScoreComponent.swift
  Fiero/Views/DesignSystem/Components/ScoreControllers/ScoreController3-4/ScoreController3-4Component.swift
Labels: Feature ✨, UI 🎨, Improvements ❤️‍🩹

#262 Login Alert Error
  Fiero/Views/Login/AccountLoginView.swift
Labels: bugfix 🧯, Improvements ❤️‍🩹

#263 fix: adjust localizable strings
  Fiero.xcodeproj/project.pbxproj
  Fiero/Lottie/blockCategory.json
  Fiero/Member.swift
  Fiero/Views/Challenges/Quick/Details/ChallengeListCell.swift
  Fiero/Views/Challenges/Quick/Details/DetailsAlertCases.swift
  Fiero/Views/Challenges/Quick/QCCategorySelectionView.swift
  Fiero/Views/Challenges/Quick/QCSelectParticipantsView.swift
  Fiero/Views/DesignSystem/Components/Button/ButtonComponent.swift
  Fiero/Views/DesignSystem/Components/Card/CategoryView/ChallengeCategoryCardView.swift
  Fiero/Views/DesignSystem/Components/Checkbox/CheckboxComponent.swift
  Fiero/Views/DesignSystem/Components/ScoreControllers/Duel/DuelScoreComponent.swift
  Fiero/Views/DesignSystem/Components/ScoreControllers/ScoreController3-4/ScoreController3-4Component.swift
  Fiero/Views/Login/LoginAlertCases.swift
  Fiero/Views/Login/SignupAlertCases.swift
  Fiero/Views/Profile/ProfileView.swift
  en.lproj/Localizable.strings
  pt-BR.lproj/Localizable.strings
Labels: UI 🎨, Improvements ❤️‍🩹, Accessibility ♥️

#266 Bugfix/tap gesture points
  Fiero/Views/DesignSystem/Components/ScoreControllers/Duel/DuelScoreComponent.swift
  Fiero/Views/DesignSystem/Components/ScoreControllers/ScoreController3-4/ScoreController3-4Component.swift
  Fiero/Views/Login/AccountLoginView.swift
Labels: bugfix 🧯, UI 🎨
