Repository MarinaFX/Fiero, pull requests merged in 2022-08, with the labels that each got.

#95 Feature/TK21 Develop Challenge Details Screen
  Fiero.xcodeproj/project.pbxproj
  Fiero/Assets/Assets.xcassets/Details/Colors/Contents.json
  Fiero/Assets/Assets.xcassets/Details/Colors/ParticipantColor.colorset/Contents.json
  Fiero/Assets/Assets.xcassets/Details/Contents.json
  Fiero/Views/ChallengeDetails/ChallengeDetailsScreenView.swift
  Fiero/Views/DesignSystem/Components/Button/ButtonStyles.swift
  Fiero/Views/DesignSystem/Components/Details/GroupComponent.swift
  Fiero/Views/DesignSystem/Components/Details/ParticipantComponent.swift
  Fiero/Views/DesignSystem/Components/Details/ParticipantStyles.swift
Labels: Feature, UI

#117 TK 23 Develop Front-end Cell Component Of Challenges List
  Fiero.xcodeproj/project.pbxproj
  Fiero/Extensions/View+Extensions.swift
  Fiero/Views/DesignSystem/Components/List/ChallengeCell/CustomTitleImageListRow.swift
Labels: UI

#89 Improvement/TK 33 Adjust Voice Over on Login & Registration Screens Components
  Fiero.xcodeproj/project.pbxproj
  Fiero.xcodeproj/xcshareddata/xcschemes/Fiero.xcscheme
  Fiero/Views/DesignSystem/Components/Alert/AlertComponent.swift
  Fiero/Views/DesignSystem/Components/Button/ButtonComponent.swift
  Fiero/Views/DesignSystem/Components/Checkbox/CheckboxComponent.swift
  Fiero/Views/DesignSystem/Components/TextFields/CustomTextFieldView.swift
  Fiero/Views/Login/AccountLoginView.swift
  Fiero/Views/Login/RegistrationScreenView.swift
  Fiero/Views/Login/TermsOfUseSheetView.swift
Labels: UI, Improvements

#118 TK 10 Develop Front-end Challenge List Fixes
  Fiero.xcodeproj/project.pbxproj
  Fiero/Assets/Assets.xcassets/ChallengesList/Contents.json
  Fiero/Assets/Assets.xcassets/ChallengesList/EmptyBox.imageset/Contents.json
  Fiero/Assets/Assets.xcassets/ChallengesList/EmptyBox.imageset/Empty box 1@1x.png
  Fiero/Assets/Assets.xcassets/ChallengesList/EmptyBox.imageset/Empty box 1@2x.png
  Fiero/Assets/Assets.xcassets/ChallengesList/EmptyBox.imageset/Empty box 1@3x.png
  Fiero/QuickChallengeResponse.swift
  Fiero/ViewModel/ChallengeListViewModel.swift
  Fiero/Views/Challenges/ChallengesListScreenView.swift
  Fiero/Views/Challenges/EmptyChallengesView.swift
  Fiero/Views/Challenges/ListWithoutSeparator.swift
  Fiero/Views/ContentView.swift
Labels: Feature

#120 feat: implemented empty state view
  Fiero/Assets/Assets.xcassets/EmptyState.imageset/Contents.json
  Fiero/Assets/Assets.xcassets/EmptyState.imageset/Empty box 1.png
  Fiero/Assets/Assets.xcassets/EmptyState.imageset/Empty box 1@2x.png
  Fiero/Assets/Assets.xcassets/EmptyState.imageset/Empty box 1@3x.png
  Fiero/Views/Challenges/EmptyChallengesView.swift
Labels: UI

#121 Feature/TK44 Develop Front/Back-end Integration On Quick Challenges Creation
  Fiero.xcodeproj/project.pbxproj
  Fiero.xcodeproj/xcuserdata/marinadepazzi.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  Fiero/Extensions/Enums/QCType.swift
  Fiero/Extensions/HTTPClient.swift
  Fiero/Extensions/URLSession+Extensions.swift
  Fiero/ViewModel/QuickChallengeViewModel.swift
  Fiero/ViewModel/UserLoginViewModel.swift
  Fiero/Views/Challenges/Quick/Amount/QCAmountWinRulesView.swift
  Fiero/Views/Challenges/Quick/QCChallengeCreatedView.swift
  Fiero/Views/DesignSystem/Components/List/ListWithoutSeparator.swift
  Fiero/Views/DesignSystem/Components/TextFields/PermanentKeyboard.swift
  FieroTests/Challenges/QuickChallengeViewModelTests.swift
  FieroTests/Login+Registration/MockKeyValueStorage.swift
Labels: Back-end

#123 Feature/TK46 develop front/back end integration on challenges list screen
  Fiero.xcodeproj/project.pbxproj
  Fiero.xcodeproj/xcuserdata/marinadepazzi.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  Fiero/Assets/Assets.xcassets/ChallengesList/Contents.json
  Fiero/Assets/Assets.xcassets/ChallengesList/EmptyBox.imageset/Contents.json
  Fiero/Assets/Assets.xcassets/ChallengesList/EmptyBox.imageset/Empty box 1@1x.png
  Fiero/Assets/Assets.xcassets/ChallengesList/EmptyBox.imageset/Empty box 1@2x.png
  Fiero/Assets/Assets.xcassets/ChallengesList/EmptyBox.imageset/Empty box 1@3x.png
  Fiero/Extensions/Enums/HTTPResult.swift
  Fiero/Extensions/Publisher+Extensions.swift
  Fiero/Extensions/URLSession+Extensions.swift
  Fiero/Member.swift
  Fiero/QuickChallenge.swift
  Fiero/QuickChallengeResponse.swift
  Fiero/QuickChallengeResponses.swift
  Fiero/Team.swift
  Fiero/ViewModel/ChallengeListViewModel.swift
  Fiero/ViewModel/QuickChallengeViewModel.swift
  Fiero/Views/Challenges/ChallengesListScreenView.swift
  Fiero/Views/Challenges/EmptyChallengesView.swift
  Fiero/Views/Challenges/Quick/Amount/QCAmountWinRulesView.swift
  Fiero/Views/Challenges/Quick/QCCategorySelectionView.swift
  Fiero/Views/Challenges/Quick/QCChallengeCreatedView.swift
  Fiero/Views/DesignSystem/Components/List/ListWithoutSeparator.swift
Labels: Back-end

#122 Feature/TK15 Develop Front-end of First Variation Screen of Ongoing Challenge (Duel)
  Fiero.xcodeproj/project.pbxproj
  Fiero/Views/DesignSystem/Components/ScoreControllers/Duel/DuelScoreComponent.swift
  Fiero/Views/DesignSystem/Components/ScoreControllers/Duel/DuelScoreStyle.swift
  Fiero/Views/OngoingQuickChallenge/OngoingDuelScreenView.swift
Labels: Feature, UI

#124 Feature/tk17 score controller component
  Fiero.xcodeproj/project.pbxproj
  Fiero/Views/Challenges/Quick/Details/ChallengeDetailsScreenView.swift
  Fiero/Views/Challenges/Quick/Ongoing/OngoingDuelScreenView.swift
  Fiero/Views/DesignSystem/Components/ScoreController3-4/ScoreController3-4Component.swift
Labels: Feature, UI

#125 Feature/TK18 Develop Front-end Scoreboard Component of Ongoing Challenge Screen (3/4 Participants)
  Fiero.xcodeproj/project.pbxproj
  Fiero/Assets/Assets.xcassets/Scoreboard/Colors/Contents.json
  Fiero/Assets/Assets.xcassets/Scoreboard/Colors/ParticipantColor1.colorset/Contents.json
  Fiero/Assets/Assets.xcassets/Scoreboard/Colors/ParticipantColor2.colorset/Contents.json
  Fiero/Assets/Assets.xcassets/Scoreboard/Colors/ParticipantColor3.colorset/Contents.json
  Fiero/Assets/Assets.xcassets/Scoreboard/Colors/ParticipantColor4.colorset/Contents.json
  Fiero/Assets/Assets.xcassets/Scoreboard/Contents.json
  Fiero/Views/Challenges/Quick/Details/ChallengeDetailsScreenView.swift
  Fiero/Views/DesignSystem/Components/Details/GroupComponent.swift
  Fiero/Views/DesignSystem/Components/Details/ParticipantStyles.swift
  Fiero/Views/DesignSystem/Components/ScoreControllers/ScoreController3-4/ScoreController3-4Component.swift
  Fiero/Views/DesignSystem/Components/Scoreboard/Components/GroupComponent.swift
  Fiero/Views/DesignSystem/Components/Scoreboard/Components/ParticipantComponent.swift
  Fiero/Views/DesignSystem/Components/Scoreboard/Styles/ElementsStyles.swift
  Fiero/Views/DesignSystem/Components/Scoreboard/Styles/ParticipantStyles.swift
Labels: Feature, UI

#126 Feature/TK68 Develop Segue To Challenge Details
  Fiero.xcodeproj/project.pbxproj
  Fiero/App/FieroApp.swift
  Fiero/Views/Challenges/ChallengesListScreenView.swift
  Fiero/Views/Challenges/Quick/Details/ChallengeDetailsView.swift
  Fiero/Views/Challenges/Quick/QCCategorySelectionView.swift
  Fiero/Views/DesignSystem/Components/List/ChallengeCell/CustomTitleImageListRow.swift
Labels: UI, Improvements

#127 TK16_Develop Front-end of Second Variation Screen of Ongoing Challenge (3/4 Participants)
  Fiero.xcodeproj/project.pbxproj
  Fiero/Member.swift
  Fiero/Team.swift
  Fiero/Views/Challenges/Quick/Ongoing/Ongoing3_4ScreenView.swift
  Fiero/Views/DesignSystem/Components/ScoreControllers/ScoreController3-4/ScoreController3-4Component.swift
  Fiero/Views/DesignSystem/Components/Scoreboard/Components/GroupComponent.swift
Labels: Feature, UI

#128 Feature/TK14 Develop Front-end Pause/Play Screen of Ongoing Challenge
  Fiero.xcodeproj/project.pbxproj
  Fiero/Views/Challenges/Quick/Ongoing/DuelScreenView.swift
  Fiero/Views/Challenges/Quick/Ongoing/OngoingDuelScreenView.swift
  Fiero/Views/Challenges/Quick/Ongoing/PauseScreen.swift
Labels: Feature, UI

#129 Bugfix/tk72 binding group component
  Fiero/Member.swift
  Fiero/Views/Challenges/Quick/Details/ChallengeDetailsView.swift
  Fiero/Views/Challenges/Quick/Ongoing/Ongoing3_4ScreenView.swift
  Fiero/Views/DesignSystem/Components/Scoreboard/Components/GroupComponent.swift
  Fiero/Views/DesignSystem/Components/Scoreboard/Components/ParticipantComponent.swift
Labels: bugfix, UI

#130 Feature/TK70 Develop Front-end Integration Of Playable Challenge Screens
  .gitignore
  Fiero.xcodeproj/xcuserdata/illuminaty.xcuserdatad/xcschemes/xcschememanagement.plist
  Fiero.xcodeproj/xcuserdata/marinadepazzi.xcuserdatad/xcschemes/xcschememanagement.plist
  Fiero/Extensions/URLSession+Extensions.swift
  Fiero/ViewModel/QuickChallengeViewModel.swift
  Fiero/Views/Challenges/ChallengesListScreenView.swift
  Fiero/Views/Challenges/Quick/Details/ChallengeDetailsView.swift
  Fiero/Views/Challenges/Quick/Ongoing/Ongoing3_4ScreenView.swift
  Fiero/Views/Challenges/Quick/Ongoing/OngoingDuelScreenView.swift
  Fiero/Views/DesignSystem/Components/ScoreControllers/ScoreController3-4/ScoreController3-4Component.swift
Labels: UI

#162 feat: refact viewmodels + list update without pull to refresh
  Fiero/App/FieroApp.swift
  Fiero/QuickChallengeResponses.swift
  Fiero/ViewModel/QuickChallengeViewModel.swift
  Fiero/Views/Challenges/ChallengesListScreenView.swift
  Fiero/Views/Challenges/EmptyChallengesView.swift
  Fiero/Views/Challenges/Quick/Amount/QCAmountWinRulesView.swift
  Fiero/Views/Challenges/Quick/QCChallengeCreatedView.swift
  Fiero/Views/ContentView.swift
  FieroTests/Challenges/QuickChallengeViewModelTests.swift
Labels: UI 🎨, Back-end ⚙️, Improvements ❤️‍🩹, WIP 🚧

#152 Improvement/TK10 Develop Transparancy Fix on Duel Score Controller Component
  Fiero.xcodeproj/xcuserdata/illuminaty.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  Fiero/Views/Challenges/Quick/Ongoing/OngoingDuelScreenView.swift
  Fiero/Views/DesignSystem/Components/ScoreControllers/Duel/DuelScoreComponent.swift
  Fiero/Views/DesignSystem/Components/ScoreControllers/Duel/DuelScoreStyle.swift
  Fiero/Views/DesignSystem/Tokens.swift
Labels: bugfix 🧯, UI 🎨, Improvements ❤️‍🩹

#161 Feature/tk999 automatic user login
  Fiero/ViewModel/UserLoginViewModel.swift
  Fiero/ViewModel/UserRegistrationViewModel.swift
  Fiero/Views/ContentView.swift
  Fiero/Views/DesignSystem/Components/TextFields/CustomTextFieldView.swift
  Fiero/Views/DesignSystem/Tokens.swift
  Fiero/Views/Login/AccountLoginView.swift
  Fiero/Views/Login/RegistrationScreenView.swift
Labels: UI 🎨, Improvements ❤️‍🩹

#163 Update terms of use
  Fiero/Views/Login/TermsOfUseSheetView.swift
Labels: UI 🎨, Improvements ❤️‍🩹

#164 wip-feat: implemented alert
  Fiero/Views/Challenges/Quick/Details/ChallengeDetailsView.swift
Labels: UI 🎨, Improvements ❤️‍🩹

#165 Create Profile Picture Component
  Fiero.xcodeproj/project.pbxproj
  Fiero.xcodeproj/xcuserdata/marcelodiefenbach.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  Fiero/QuickChallenge.swift
  Fiero/Views/Challenges/ChallengesListScreenView.swift
  Fiero/Views/Challenges/EmptyChallengesView.swift
  Fiero/Views/Challenges/Quick/Details/ChallengeDetailsView.swift
  Fiero/Views/Challenges/Quick/QCCategorySelectionView.swift
  Fiero/Views/ContentView.swift
  Fiero/Views/DesignSystem/Components/ProfilePictureComponent/Profile Picture Component.swift
  Fiero/Views/Profile/ProfileView.swift
  Fiero/Views/Profile/ProfileViewModel.swift
  Fiero/Views/TabBar.swift
Labels: UI 🎨

#167 Feature/TK 27 Develop Front-end Integration for Ongoing Screens
  .gitignore
  Fiero.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Fiero.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Fiero.xcodeproj/xcuserdata/illuminaty.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  Fiero.xcodeproj/xcuserdata/marcelodiefenbach.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  Fiero/Extensions/View+Extensions.swift
  Fiero/ViewModel/QuickChallengeViewModel.swift
  Fiero/Views/Challenges/ChallengesListScreenView.swift
  Fiero/Views/Challenges/EmptyChallengesView.swift
  Fiero/Views/Challenges/Quick/Amount/QCAmountWinRulesView.swift
  Fiero/Views/Challenges/Quick/Details/ChallengeDetailsView.swift
  Fiero/Views/Challenges/Quick/Ongoing/DuelScreenView.swift
  Fiero/Views/Challenges/Quick/Ongoing/Ongoing3_4ScreenView.swift
  Fiero/Views/Challenges/Quick/Ongoing/PauseScreen.swift
  Fiero/Views/Challenges/Quick/QCChallengeCreatedView.swift
  Fiero/Views/DesignSystem/Components/Button/ButtonStyles.swift
  Fiero/Views/TabBar.swift
Labels: Feature ✨, UI 🎨

#169 Bugfix/tk3 develop list deletion fix
  Fiero/Extensions/URLSession+Extensions.swift
  Fiero/QuickChallenge.swift
  Fiero/ViewModel/QuickChallengeViewModel.swift
  Fiero/Views/Challenges/ChallengesListScreenView.swift
  Fiero/Views/Challenges/Quick/Details/ChallengeDetailsView.swift
Labels: bugfix 🧯, UI 🎨, Back-end ⚙️, Improvements ❤️‍🩹

#170 Change background color of button .black variant
  Fiero/Views/DesignSystem/Components/Button/ButtonStyles.swift
Labels: UI 🎨, Improvements ❤️‍🩹

#176 Feature/TK12 Develop Front Back End Integration Of Pause Play Screen Of Ongoing Challenges
  Fiero/Extensions/URLSession+Extensions.swift
  Fiero/Member.swift
  Fiero/QuickChallengeResponses.swift
  Fiero/ViewModel/QuickChallengeViewModel.swift
  Fiero/ViewModel/UserRegistrationViewModel.swift
  Fiero/Views/Challenges/ChallengesListScreenView.swift
  Fiero/Views/Challenges/Quick/Details/ChallengeDetailsView.swift
  Fiero/Views/Challenges/Quick/Ongoing/DuelScreenView.swift
  Fiero/Views/Challenges/Quick/Ongoing/Ongoing3_4ScreenView.swift
  Fiero/Views/Challenges/Quick/Ongoing/OngoingDuelScreenView.swift
  Fiero/Views/Challenges/Quick/Ongoing/PauseScreen.swift
  Fiero/Views/Challenges/Quick/QCChallengeCreatedView.swift
  Fiero/Views/DesignSystem/Components/ScoreControllers/Duel/DuelScoreComponent.swift
  Fiero/Views/DesignSystem/Components/ScoreControllers/ScoreController3-4/ScoreController3-4Component.swift
Labels: Feature ✨, UI 🎨, Back-end ⚙️

#171 Improvement/tk59 back button on challenge details screen
  Fiero/Views/Challenges/ChallengesListScreenView.swift
  Fiero/Views/Challenges/Quick/Details/ChallengeDetailsView.swift
Labels: UI 🎨, Improvements ❤️‍🩹

#172 fix color of tab bar on ios 14
  Fiero/Views/TabBar.swift
Labels: bug 🐞, UI 🎨

#168 Implement alert when fetching user challenges return error
  Fiero/ViewModel/QuickChallengeViewModel.swift
  Fiero/Views/Challenges/ChallengesListScreenView.swift
Labels: UI 🎨, Improvements ❤️‍🩹

#184 Tk UI improvements after ops review
  Fiero/Member.swift
  Fiero/Views/Challenges/Quick/Amount/QCAmountWinRulesView.swift
  Fiero/Views/Challenges/Quick/Details/ChallengeDetailsView.swift
  Fiero/Views/Challenges/Quick/Ongoing/Ongoing3_4ScreenView.swift
  Fiero/Views/Challenges/Quick/QCCategorySelectionView.swift
  Fiero/Views/Challenges/Quick/QCNamingView.swift
  Fiero/Views/Challenges/Quick/QCSelectParticipantsView.swift
  Fiero/Views/DesignSystem/Components/Card/ChallengeCategoryCardView.swift
  Fiero/Views/DesignSystem/Components/ScoreControllers/ScoreController3-4/ScoreController3-4Component.swift
  Fiero/Views/DesignSystem/Components/Scoreboard/Components/ParticipantComponent.swift
  Fiero/Views/DesignSystem/Tokens.swift
  Fiero/Views/GIfImage.swift
  Fiero/Views/TabBar.swift
Labels: UI 🎨, Improvements ❤️‍🩹

#185 Improvement/tk9999 develop failure alerts details screen
  Fiero.xcodeproj/project.pbxproj
  Fiero/ViewModel/QuickChallengeViewModel.swift
  Fiero/ViewModel/UserLoginViewModel.swift
  Fiero/ViewModel/UserRegistrationViewModel.swift
  Fiero/Views/Challenges/EmptyChallengesView.swift
  Fiero/Views/Challenges/Quick/Details/ChallengeDetailsView.swift
  Fiero/Views/Challenges/Quick/Details/DetailsAlertCases.swift
  Fiero/Views/Challenges/Quick/QCChallengeCreatedView.swift
  Fiero/Views/Challenges/Quick/QCNamingView.swift
  Fiero/Views/Challenges/WIP/Time/TimePickerSelectionView.swift
  Fiero/Views/Login/RegistrationScreenView.swift
Labels: bugfix 🧯, Improvements ❤️‍🩹, Combine 🪖

#186 fix overflow when component show 4 participants
  Fiero/Member.swift
  Fiero/Views/Challenges/Quick/Details/ChallengeDetailsView.swift
  Fiero/Views/DesignSystem/Components/Scoreboard/Components/GroupComponent.swift
  Fiero/Views/DesignSystem/Tokens.swift
  Fiero/Views/Login/AccountLoginView.swift
Labels: bugfix 🧯, UI 🎨

#174 Improvement/TK23 Develop UserDefaults Key for Player Picture and Name
  Fiero/ViewModel/UserRegistrationViewModel.swift
  Fiero/Views/Login/AccountLoginView.swift
  Fiero/Views/Login/RegistrationScreenView.swift
  Fiero/Views/Profile/ProfileViewModel.swift
Labels: UI 🎨, Back-end ⚙️, Improvements ❤️‍🩹

#166 Implement long press count
  Fiero/ViewModel/QuickChallengeViewModel.swift
  Fiero/ViewModel/UserLoginViewModel.swift
  Fiero/ViewModel/UserRegistrationViewModel.swift
  Fiero/Views/Challenges/Quick/Ongoing/Ongoing3_4ScreenView.swift
  Fiero/Views/Challenges/Quick/Ongoing/OngoingDuelScreenView.swift
  Fiero/Views/DesignSystem/Components/Card/ChallengeCategoryCardView.swift
  Fiero/Views/DesignSystem/Components/ScoreControllers/Duel/DuelScoreComponent.swift
  Fiero/Views/DesignSystem/Components/ScoreControllers/ScoreController3-4/ScoreController3-4Component.swift
Labels: UI 🎨, Improvements ❤️‍🩹

#198 Remove forgotten password on login screen
  Fiero/Views/Login/AccountLoginView.swift
Labels: UI 🎨

#199 change token of style font to callout
  Fiero/Views/Login/AccountLoginView.swift
Labels: UI 🎨

#200 Hide navigation bar
  Fiero/Views/Challenges/Quick/Ongoing/Ongoing3_4ScreenView.swift
Labels: UI 🎨

#201 Remove back button on ongoing screen 3/4
  Fiero/Views/Challenges/Quick/Ongoing/Ongoing3_4ScreenView.swift
Labels: UI 🎨

#202 add tokens to fix color of progressBar
  Fiero/Views/Challenges/Quick/Amount/QCAmountWinRulesView.swift
Labels: UI 🎨

#203 remove dismiss button of keyboard
  Fiero/Views/DesignSystem/Components/TextFields/PermanentKeyboard.swift
Labels: UI 🎨

#204 implement getname to get the correct string on screen
  Fiero/Views/Challenges/Quick/Ongoing/OngoingDuelScreenView.swift
Labels: UI 🎨

#205 add token of border small on corner radios modifier
  Fiero/Views/DesignSystem/Components/Card/ChallengeParticipantsSelectionCardView.swift
Labels: UI 🎨

#206 correct pattern of buttons o create challenge flow
  Fiero/Views/Challenges/Quick/Amount/QCAmountWinRulesView.swift
Labels: UI 🎨

#207 fix: checkbox behavaior and alert
  Fiero/Views/Login/RegistrationScreenView.swift
Labels: UI 🎨, Improvements ❤️‍🩹

#208 Correct Challenge Name in Pause Screen
  Fiero/Views/Challenges/Quick/Ongoing/PauseScreen.swift
Labels: bugfix 🧯, UI 🎨

#209 Bug Fix/TK5 Terms of use w bold without underline
  Fiero/Views/DesignSystem/Components/Checkbox/CheckboxComponent.swift
  Fiero/Views/DesignSystem/Components/Checkbox/CheckboxStyles.swift
  Fiero/Views/Login/RegistrationScreenView.swift
Labels: bugfix 🧯, UI 🎨, Improvements ❤️‍🩹

#210 remove lightining emoji
  Fiero/Views/Challenges/Quick/Details/ChallengeDetailsView.swift
Labels: UI 🎨

#211 Improvement/TK 23 Bold text on challenge creation cards
  Fiero/Views/DesignSystem/Components/Card/ChallengeCategoryCardView.swift
Labels: UI 🎨, Improvements ❤️‍🩹

#216 fix token of getColor and change labels to lowPure to improve contrast
  Fiero/Member.swift
  Fiero/Views/Challenges/Quick/Details/ChallengeDetailsView.swift
  Fiero/Views/DesignSystem/Components/ScoreControllers/ScoreController3-4/ScoreController3-4Component.swift
Labels: UI 🎨

#217 Tk16 haptics and success(low priority feature)
  Fiero.xcodeproj/project.pbxproj
  Fiero/Assets/GIfImage.swift
  Fiero/Extensions/Haptics.swift
  Fiero/Views/Challenges/ChallengesListScreenView.swift
  Fiero/Views/Challenges/Quick/Details/ChallengeDetailsView.swift
  Fiero/Views/Challenges/Quick/Ongoing/Ongoing3_4ScreenView.swift
  Fiero/Views/Challenges/Quick/Ongoing/OngoingDuelScreenView.swift
  Fiero/Views/Challenges/Quick/QCCategorySelectionView.swift
  Fiero/Views/DesignSystem/Components/Button/ButtonComponent.swift
  Fiero/Views/DesignSystem/Components/ScoreControllers/Duel/DuelScoreComponent.swift
  Fiero/Views/DesignSystem/Components/ScoreControllers/ScoreController3-4/ScoreController3-4Component.swift
Labels: UI 🎨

#218 Change Button Text Label After Starting a Challenge
  Fiero/Views/Challenges/Quick/Details/ChallengeDetailsView.swift
Labels: UI 🎨, Improvements ❤️‍🩹

#220 Implement Alert When Challenge Is Not Created
  Fiero/ViewModel/QuickChallengeViewModel.swift
  Fiero/Views/Challenges/Quick/Amount/QCAmountWinRulesView.swift
Labels: UI 🎨, Improvements ❤️‍🩹

#219 Change "Ir para lista de desafios" to "Detalhes"
  Fiero/Views/Challenges/Quick/Ongoing/PauseScreen.swift
Labels: UI 🎨, Improvements ❤️‍🩹

#222 Tk41 create lottie class and implement animations
  Fiero.xcodeproj/project.pbxproj
  Fiero/Lottie.swift
  Fiero/Lottie/animation.geojson
  Fiero/Lottie/animation.json
  Fiero/Lottie/loading.json
  Fiero/Lottie/tonto.json
  Fiero/ViewModel/UserLoginViewModel.swift
  Fiero/ViewModel/UserRegistrationViewModel.swift
  Fiero/Views/Challenges/EmptyChallengesView.swift
  Fiero/Views/Challenges/Quick/Details/ChallengeDetailsView.swift
  Fiero/Views/DesignSystem/Components/Card/ChallengeCategoryCardView.swift
  Fiero/Views/Login/AccountLoginView.swift
  Fiero/Views/Login/RegistrationScreenView.swift
Labels: UI 🎨, Improvements ❤️‍🩹

#223 Tk8 check bottom buttons padding from login signup
  Fiero/Views/DesignSystem/Components/TextFields/CustomTextFieldView.swift
  Fiero/Views/Login/AccountLoginView.swift
  Fiero/Views/Login/RegistrationScreenView.swift
Labels: UI 🎨, Improvements ❤️‍🩹
